baseURL: "https://muhammadri.co/"
title: Rico Ardiansyah's Blog
paginate: 10
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableGitInfo: true
frontmatter:
  lastmod:
  - lastmod
  - :git
  - date
  - publishDate

googleAnalytics: G-5MY9QDXY3P

minify:
  disableXML: true
  minifyOutput: true
outputs:
      home:
          - HTML
          - RSS
          - JSON # is necessary
params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Rico Ardiansyah's Blog
  description: "Welcome to my blog. Blog static cuman buat dokumentasi dan sharing-sharing biar gak lupa hehe kadang juga suka nulis random"
  keywords: [Rico Ardiansyah Blog, Portfolio, Muhammad Rico Ardiansyah]
  author: Rico Ardiansyah
  # author: ["Me", "You"] # multiple authors
  images: "/img"
  DateFormat: "2 January 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  #disqusShortname: blog-rico
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    disableFingerprinting: true
    favicon: "/img/terminal.ico"
    favicon16x16: "/img/terminal.ico"
    favicon32x32: "/img/terminal.ico"
    apple_touch_icon: "/img/terminal.ico"
    safari_pinned_tab: "/img/terminal.ico"

  label:
    text: "⚡️Rico's Blog"
    icon: /apple-touch-icon.png
    iconHeight: 30

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: ⚡️Rico's Blog
    subtitle: "Welcome"
    imageUrl: "<img location>"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Blog static cuman buat dokumentasi dan sharing-sharing biar gak lupa hehe kadang juga suka nulis random

  socialIcons:
    - name: twitter
      url: "https://twitter.com/ardiansyah_w404"
    - name: github
      url: "https://github.com/0xricoard"
    - name: instagram
      url: "https://instagram.com/0xricoard"
    - name: linkedin
      url: "https://id.linkedin.com/in/muhammad-rico-ardiansyah-8049a8244"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  #editPost:
    #URL: "https://github.com/0xricoard/hugo-blog/tree/main/content/"
    #Text: "Suggest Changes" # edit text
    #appendFilePath: false # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: archive
      name: Archive
      url: /archives/
      weight: 20
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 30
    - identifier: contact
      name: Contact
      url: https://t.me/ardiansyah_w404
      weight: 40
    - identifier: About
      name: About
      url: /posts/about
      weight: 10
    - name: Search
      url: search/
      weight: 50
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
    
includeNewer: false
threshold: 80
toLower: false
related:
  indices:
    - name: categories
      weight: 100
    - name: tags
      weight: 100
    - name: date
      weight: 10
